Reinstate atca_delay_ms() and atca_delay_us() as previous commit broke the build.
E.G

LD /scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/esp32_dev_mgos.elf
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/mosapp/libmosapp.a(mgos_atca_hal.o): In function `mgos_atca_hal_i2c_receive':
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/deps/atca/src/mgos_atca_hal.c:96: undefined reference to `atca_delay_us'
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/mosapp/libmosapp.a(mgos_atca_hal.o): In function `mgos_atca_hal_i2c_wake':
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/deps/atca/src/mgos_atca_hal.c:126: undefined reference to `atca_delay_us'
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/mosapp/libmosapp.a(atca_execution.o):(.text.atca_execute_command+0x4): undefined reference to `atca_delay_ms'
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/mosapp/libmosapp.a(atca_execution.o): In function `atca_execute_command':
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/deps/atca/cryptoauthlib/lib/atca_execution.c:307: undefined reference to `atca_delay_ms'
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/deps/atca/cryptoauthlib/lib/atca_execution.c:326: undefined reference to `atca_delay_ms'
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/mosapp/libmosapp.a(atca_iface.o): In function `atwake':
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/deps/atca/cryptoauthlib/lib/atca_iface.c:201: undefined reference to `atca_delay_ms'
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/mosapp/libmosapp.a(atca_iface.o): In function `atidle':
/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/deps/atca/cryptoauthlib/lib/atca_iface.c:201: undefined reference to `atca_delay_ms'
collect2: error: ld returned 1 exit status
/opt/Espressif/esp-idf/make/project.mk:482: recipe for target '/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/esp32_dev_mgos.elf' failed
make: *** [/scratch/git_repos/mqtt_yview/embedded/y_hw/ysmartmeter/software/esp32_dev_mgos/build/objs/esp32_dev_mgos.elf] Error 1